// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmsnNZ7PS7ZWWeP48EMzbJP8oz0e6U7Qo',
    appId: '1:942480474235:web:3f97e7742145f1f72de2de',
    messagingSenderId: '942480474235',
    projectId: 'water-meter-reader-65aff',
    authDomain: 'water-meter-reader-65aff.firebaseapp.com',
    databaseURL: 'https://water-meter-reader-65aff-default-rtdb.firebaseio.com',
    storageBucket: 'water-meter-reader-65aff.firebasestorage.app',
    measurementId: 'G-DJHF2PK5Z3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1WuK2GXZyd9sD6-dOmId6SW7m8wura5o',
    appId: '1:942480474235:android:601e5a0a9039cc9b2de2de',
    messagingSenderId: '942480474235',
    projectId: 'water-meter-reader-65aff',
    databaseURL: 'https://water-meter-reader-65aff-default-rtdb.firebaseio.com',
    storageBucket: 'water-meter-reader-65aff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0NfMuHHCLsgnfgrSk5mKRrXNoBDU33Tw',
    appId: '1:942480474235:ios:3de9c8cd407d51e72de2de',
    messagingSenderId: '942480474235',
    projectId: 'water-meter-reader-65aff',
    databaseURL: 'https://water-meter-reader-65aff-default-rtdb.firebaseio.com',
    storageBucket: 'water-meter-reader-65aff.firebasestorage.app',
    iosBundleId: 'com.example.waterMeterElectronicReader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0NfMuHHCLsgnfgrSk5mKRrXNoBDU33Tw',
    appId: '1:942480474235:ios:3de9c8cd407d51e72de2de',
    messagingSenderId: '942480474235',
    projectId: 'water-meter-reader-65aff',
    databaseURL: 'https://water-meter-reader-65aff-default-rtdb.firebaseio.com',
    storageBucket: 'water-meter-reader-65aff.firebasestorage.app',
    iosBundleId: 'com.example.waterMeterElectronicReader',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmsnNZ7PS7ZWWeP48EMzbJP8oz0e6U7Qo',
    appId: '1:942480474235:web:d448bc95d4b499352de2de',
    messagingSenderId: '942480474235',
    projectId: 'water-meter-reader-65aff',
    authDomain: 'water-meter-reader-65aff.firebaseapp.com',
    databaseURL: 'https://water-meter-reader-65aff-default-rtdb.firebaseio.com',
    storageBucket: 'water-meter-reader-65aff.firebasestorage.app',
    measurementId: 'G-HN19HXKRXY',
  );
}
