// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD95OlBdkv4uv70UOr0Q47cmaRu-0qR130',
    appId: '1:121888539189:web:4ee78a91e4ee93dbf2a77c',
    messagingSenderId: '121888539189',
    projectId: 'water-meter-reader-group6',
    authDomain: 'water-meter-reader-group6.firebaseapp.com',
    databaseURL: 'https://water-meter-reader-group6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'water-meter-reader-group6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSfByOobsDQ_MfJFND1y6GG_ZkLiGfDyM',
    appId: '1:121888539189:android:4a8a5e8bc9f7e290f2a77c',
    messagingSenderId: '121888539189',
    projectId: 'water-meter-reader-group6',
    databaseURL: 'https://water-meter-reader-group6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'water-meter-reader-group6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUb5ruQ7ra_qBi-94vqBF_cC4FeREbr3s',
    appId: '1:121888539189:ios:697573cd3753631af2a77c',
    messagingSenderId: '121888539189',
    projectId: 'water-meter-reader-group6',
    databaseURL: 'https://water-meter-reader-group6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'water-meter-reader-group6.firebasestorage.app',
    iosBundleId: 'com.example.waterMeterElectronicReader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUb5ruQ7ra_qBi-94vqBF_cC4FeREbr3s',
    appId: '1:121888539189:ios:697573cd3753631af2a77c',
    messagingSenderId: '121888539189',
    projectId: 'water-meter-reader-group6',
    databaseURL: 'https://water-meter-reader-group6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'water-meter-reader-group6.firebasestorage.app',
    iosBundleId: 'com.example.waterMeterElectronicReader',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD95OlBdkv4uv70UOr0Q47cmaRu-0qR130',
    appId: '1:121888539189:web:f6046bb3f28f64cbf2a77c',
    messagingSenderId: '121888539189',
    projectId: 'water-meter-reader-group6',
    authDomain: 'water-meter-reader-group6.firebaseapp.com',
    databaseURL: 'https://water-meter-reader-group6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'water-meter-reader-group6.firebasestorage.app',
  );

}